/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.fundacion.vistas;

/**
 *
 * @author USUARIO
 */
public class Notificaciones extends javax.swing.JFrame {

    /**
     * Creates new form Notificaciones2
     */
    public Notificaciones() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        setTitle("NOTIFICACIONES");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        PanelAsistencia = new javax.swing.JPanel();
        AlerAsis1 = new javax.swing.JLabel();
        NomEstud = new javax.swing.JLabel();
        EstudianteAler = new javax.swing.JTextField();
        Hace5min = new javax.swing.JTextField();
        InasisA = new javax.swing.JLabel();
        InasistenciaClaseDe = new javax.swing.JTextField();
        PanelPsico1 = new javax.swing.JPanel();
        Hace5minAlerInas2 = new javax.swing.JTextField();
        EstudianteAsistencia2 = new javax.swing.JTextField();
        AlerInasistencia2 = new javax.swing.JTextField();
        NomEstudi = new javax.swing.JLabel();
        InasistenA = new javax.swing.JLabel();
        PanelPsico = new javax.swing.JPanel();
        Hace5minPsico = new javax.swing.JTextField();
        EstudianteAlerPsico = new javax.swing.JTextField();
        NomEst = new javax.swing.JLabel();
        InasistenciaPsico = new javax.swing.JTextField();
        AlerPsico = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        GenerPor = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Alerta = new javax.swing.JLabel();
        TipoDeAlerta = new javax.swing.JLabel();
        AsistenciaAlert = new javax.swing.JComboBox<>();
        GeneradaPor = new javax.swing.JLabel();
        AsistenciaAler1 = new javax.swing.JComboBox<>();
        AlertEstudian3 = new javax.swing.JLabel();
        EstudianteAlerta = new javax.swing.JComboBox<>();
        Observacion = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        TipoDeAlerta1 = new javax.swing.JLabel();
        AsistenciaAlert3 = new javax.swing.JComboBox<>();
        AsistenciaAlert2 = new javax.swing.JComboBox<>();
        Alerta1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        GeneradaPor1 = new javax.swing.JLabel();
        AlertEstudian2 = new javax.swing.JLabel();
        EstudianteAlerta1 = new javax.swing.JComboBox<>();
        Observacion1 = new javax.swing.JLabel();
        PanelPsico2 = new javax.swing.JPanel();
        Hace5minPsico1 = new javax.swing.JTextField();
        EstudianteAlerPsico1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        InasistenciaPsico1 = new javax.swing.JTextField();
        AlePsicol = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        AlertEstudian1 = new javax.swing.JLabel();
        AntNot = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        Notificaciones = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        GenerarAlerta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1100, 900));
        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 900));

        PanelAsistencia.setBorder(new javax.swing.border.MatteBorder(null));

        AlerAsis1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        AlerAsis1.setText("Alerta - Asistencia 1");

        NomEstud.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        NomEstud.setText("Estudiante ");

        EstudianteAler.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        EstudianteAler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstudianteAlerActionPerformed(evt);
            }
        });

        Hace5min.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        Hace5min.setText("Hace 5 min");

        InasisA.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        InasisA.setText("Inasistencia a clase de:");

        InasistenciaClaseDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InasistenciaClaseDeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelAsistenciaLayout = new javax.swing.GroupLayout(PanelAsistencia);
        PanelAsistencia.setLayout(PanelAsistenciaLayout);
        PanelAsistenciaLayout.setHorizontalGroup(
            PanelAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAsistenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAsistenciaLayout.createSequentialGroup()
                        .addComponent(AlerAsis1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Hace5min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(NomEstud, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(InasisA, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EstudianteAler, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                        .addComponent(InasistenciaClaseDe)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        PanelAsistenciaLayout.setVerticalGroup(
            PanelAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAsistenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelAsistenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AlerAsis1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Hace5min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(NomEstud)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EstudianteAler, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InasisA)
                .addGap(12, 12, 12)
                .addComponent(InasistenciaClaseDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        PanelPsico1.setBorder(new javax.swing.border.MatteBorder(null));

        Hace5minAlerInas2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        Hace5minAlerInas2.setText("Hace 5 min");

        EstudianteAsistencia2.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        EstudianteAsistencia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstudianteAsistencia2ActionPerformed(evt);
            }
        });

        NomEstudi.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        NomEstudi.setText("Estudiante");

        InasistenA.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        InasistenA.setText("Inasistencia a clase de:");

        javax.swing.GroupLayout PanelPsico1Layout = new javax.swing.GroupLayout(PanelPsico1);
        PanelPsico1.setLayout(PanelPsico1Layout);
        PanelPsico1Layout.setHorizontalGroup(
            PanelPsico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPsico1Layout.createSequentialGroup()
                .addGroup(PanelPsico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPsico1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(NomEstudi, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelPsico1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelPsico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InasistenA, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelPsico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Hace5minAlerInas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(PanelPsico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(EstudianteAsistencia2)
                                    .addComponent(AlerInasistencia2, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE))))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        PanelPsico1Layout.setVerticalGroup(
            PanelPsico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPsico1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Hace5minAlerInas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NomEstudi, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EstudianteAsistencia2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InasistenA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AlerInasistencia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        PanelPsico.setBorder(new javax.swing.border.MatteBorder(null));
        PanelPsico.setLayout(null);

        Hace5minPsico.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        Hace5minPsico.setText("Hace 5 min");
        PanelPsico.add(Hace5minPsico);
        Hace5minPsico.setBounds(180, 10, 70, 21);

        EstudianteAlerPsico.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        EstudianteAlerPsico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstudianteAlerPsicoActionPerformed(evt);
            }
        });
        PanelPsico.add(EstudianteAlerPsico);
        EstudianteAlerPsico.setBounds(7, 57, 270, 21);

        NomEst.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        NomEst.setText("Estudiante ");
        PanelPsico.add(NomEst);
        NomEst.setBounds(7, 36, 185, 15);
        PanelPsico.add(InasistenciaPsico);
        InasistenciaPsico.setBounds(10, 110, 270, 22);

        AlerPsico.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        AlerPsico.setText("Alerta - Psicologìa");
        PanelPsico.add(AlerPsico);
        AlerPsico.setBounds(10, 10, 185, 17);

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        PanelPsico.add(jScrollPane4);
        jScrollPane4.setBounds(10, 140, 270, 70);

        GenerPor.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        GenerPor.setText("Generada Por:");
        PanelPsico.add(GenerPor);
        GenerPor.setBounds(10, 90, 79, 15);

        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.setLayout(null);

        Alerta.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Alerta.setText("Alerta");
        jPanel2.add(Alerta);
        Alerta.setBounds(20, 10, 40, 17);

        TipoDeAlerta.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        TipoDeAlerta.setText("Tipo de Alerta:");
        jPanel2.add(TipoDeAlerta);
        TipoDeAlerta.setBounds(21, 45, 81, 15);

        AsistenciaAlert.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asistencia" }));
        jPanel2.add(AsistenciaAlert);
        AsistenciaAlert.setBounds(125, 41, 160, 22);

        GeneradaPor.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        GeneradaPor.setText("Generada Por:");
        jPanel2.add(GeneradaPor);
        GeneradaPor.setBounds(20, 70, 79, 20);

        jPanel2.add(AsistenciaAler1);
        AsistenciaAler1.setBounds(125, 69, 160, 24);

        AlertEstudian3.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        AlertEstudian3.setText("Estudiante");
        jPanel2.add(AlertEstudian3);
        AlertEstudian3.setBounds(20, 100, 61, 15);

        jPanel2.add(EstudianteAlerta);
        EstudianteAlerta.setBounds(125, 97, 160, 24);

        Observacion.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        Observacion.setText("Observaciones");
        jPanel2.add(Observacion);
        Observacion.setBounds(20, 140, 83, 15);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Inasistencia a la clase de danzas\n");
        jScrollPane2.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(20, 160, 270, 150);

        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel3.setLayout(null);

        TipoDeAlerta1.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        TipoDeAlerta1.setText("Tipo de Alerta:");
        jPanel3.add(TipoDeAlerta1);
        TipoDeAlerta1.setBounds(17, 43, 81, 15);

        AsistenciaAlert3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asistencia" }));
        jPanel3.add(AsistenciaAlert3);
        AsistenciaAlert3.setBounds(121, 39, 170, 22);

        jPanel3.add(AsistenciaAlert2);
        AsistenciaAlert2.setBounds(121, 67, 170, 24);

        Alerta1.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Alerta1.setText("Alerta");
        jPanel3.add(Alerta1);
        Alerta1.setBounds(17, 7, 40, 17);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("Ingrese un comentario adicional\n\n");
        jScrollPane3.setViewportView(jTextArea2);

        jPanel3.add(jScrollPane3);
        jScrollPane3.setBounds(20, 160, 270, 150);

        GeneradaPor1.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        GeneradaPor1.setText("Generada Por:");
        jPanel3.add(GeneradaPor1);
        GeneradaPor1.setBounds(20, 70, 79, 15);

        AlertEstudian2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        AlertEstudian2.setText("Estudiante");
        jPanel3.add(AlertEstudian2);
        AlertEstudian2.setBounds(20, 100, 61, 15);

        jPanel3.add(EstudianteAlerta1);
        EstudianteAlerta1.setBounds(120, 100, 170, 24);

        Observacion1.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        Observacion1.setText("Observaciones");
        jPanel3.add(Observacion1);
        Observacion1.setBounds(20, 140, 83, 15);

        PanelPsico2.setBorder(new javax.swing.border.MatteBorder(null));
        PanelPsico2.setLayout(null);

        Hace5minPsico1.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        Hace5minPsico1.setText("Hace 5 min");
        PanelPsico2.add(Hace5minPsico1);
        Hace5minPsico1.setBounds(193, 7, 70, 21);

        EstudianteAlerPsico1.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        EstudianteAlerPsico1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstudianteAlerPsico1ActionPerformed(evt);
            }
        });
        PanelPsico2.add(EstudianteAlerPsico1);
        EstudianteAlerPsico1.setBounds(10, 60, 270, 21);

        jLabel10.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        jLabel10.setText("Estudiante ");
        PanelPsico2.add(jLabel10);
        jLabel10.setBounds(7, 36, 185, 15);
        PanelPsico2.add(InasistenciaPsico1);
        InasistenciaPsico1.setBounds(7, 109, 270, 22);

        AlePsicol.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        AlePsicol.setText("Alerta - Psicologìa");
        PanelPsico2.add(AlePsicol);
        AlePsicol.setBounds(10, 10, 185, 17);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane5.setViewportView(jTextArea3);

        PanelPsico2.add(jScrollPane5);
        jScrollPane5.setBounds(10, 140, 270, 110);

        AlertEstudian1.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        AlertEstudian1.setText("Generada Por:");
        PanelPsico2.add(AlertEstudian1);
        AlertEstudian1.setBounds(10, 90, 79, 15);

        AntNot.setBackground(new java.awt.Color(255, 255, 255));
        AntNot.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        AntNot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/fundacion/imagenes/icons8-izquierda-32.png"))); // NOI18N
        AntNot.setText("Volver");
        AntNot.setBorder(null);
        AntNot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AntNotActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Notificaciones.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        Notificaciones.setText("NOTIFICACIONES");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/fundacion/imagenes/logoFNH2.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Notificaciones)
                .addGap(105, 105, 105))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Notificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        GenerarAlerta.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        GenerarAlerta.setText("GENERAR ALERTA");
        GenerarAlerta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        GenerarAlerta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GenerarAlertaMouseClicked(evt);
            }
        });
        GenerarAlerta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerarAlertaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(GenerarAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AntNot, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PanelAsistencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PanelPsico1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelPsico, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PanelPsico2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(49, 49, 49))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(GenerarAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(PanelPsico, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(PanelPsico2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(PanelAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(PanelPsico1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addComponent(AntNot, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1109, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 866, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GenerarAlertaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GenerarAlertaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_GenerarAlertaMouseClicked

    private void GenerarAlertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerarAlertaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenerarAlertaActionPerformed

    private void EstudianteAlerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstudianteAlerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstudianteAlerActionPerformed

    private void InasistenciaClaseDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InasistenciaClaseDeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InasistenciaClaseDeActionPerformed

    private void EstudianteAsistencia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstudianteAsistencia2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstudianteAsistencia2ActionPerformed

    private void EstudianteAlerPsicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstudianteAlerPsicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstudianteAlerPsicoActionPerformed

    private void EstudianteAlerPsico1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstudianteAlerPsico1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstudianteAlerPsico1ActionPerformed

    private void AntNotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AntNotActionPerformed
        this.dispose();
        PerfilAdministrador regr = new PerfilAdministrador();
        regr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AntNotActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlePsicol;
    private javax.swing.JLabel AlerAsis1;
    private javax.swing.JTextField AlerInasistencia2;
    private javax.swing.JLabel AlerPsico;
    private javax.swing.JLabel AlertEstudian1;
    private javax.swing.JLabel AlertEstudian2;
    private javax.swing.JLabel AlertEstudian3;
    private javax.swing.JLabel Alerta;
    private javax.swing.JLabel Alerta1;
    private javax.swing.JButton AntNot;
    private javax.swing.JComboBox<String> AsistenciaAler1;
    private javax.swing.JComboBox<String> AsistenciaAlert;
    private javax.swing.JComboBox<String> AsistenciaAlert2;
    private javax.swing.JComboBox<String> AsistenciaAlert3;
    private javax.swing.JTextField EstudianteAler;
    private javax.swing.JTextField EstudianteAlerPsico;
    private javax.swing.JTextField EstudianteAlerPsico1;
    private javax.swing.JComboBox<String> EstudianteAlerta;
    private javax.swing.JComboBox<String> EstudianteAlerta1;
    private javax.swing.JTextField EstudianteAsistencia2;
    private javax.swing.JLabel GenerPor;
    private javax.swing.JLabel GeneradaPor;
    private javax.swing.JLabel GeneradaPor1;
    private javax.swing.JTextField GenerarAlerta;
    private javax.swing.JTextField Hace5min;
    private javax.swing.JTextField Hace5minAlerInas2;
    private javax.swing.JTextField Hace5minPsico;
    private javax.swing.JTextField Hace5minPsico1;
    private javax.swing.JLabel InasisA;
    private javax.swing.JLabel InasistenA;
    private javax.swing.JTextField InasistenciaClaseDe;
    private javax.swing.JTextField InasistenciaPsico;
    private javax.swing.JTextField InasistenciaPsico1;
    private javax.swing.JLabel NomEst;
    private javax.swing.JLabel NomEstud;
    private javax.swing.JLabel NomEstudi;
    private javax.swing.JLabel Notificaciones;
    private javax.swing.JLabel Observacion;
    private javax.swing.JLabel Observacion1;
    private javax.swing.JPanel PanelAsistencia;
    private javax.swing.JPanel PanelPsico;
    private javax.swing.JPanel PanelPsico1;
    private javax.swing.JPanel PanelPsico2;
    private javax.swing.JLabel TipoDeAlerta;
    private javax.swing.JLabel TipoDeAlerta1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    // End of variables declaration//GEN-END:variables
}
