/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.fundacion.vistas;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
/**
 *
 * @author USUARIO
 */
public class Perfil_estudiante extends javax.swing.JFrame {

    /**
     * Creates new form Perfil_estudiante
     */
    public Perfil_estudiante() {
        initComponents();
        this.setLocationRelativeTo(null);
        setVisible(true);
        setLocationRelativeTo(null);
        setTitle("PERFIL DEL ESTUDIANTE");
    }
//Instanciar para poder utilizar
    Perfil_estudiante pestudiante = new Perfil_estudiante(); 
    
    //Asi accedo a los metodos del registro
    Perfil_estudiante registro = new Perfil_estudiante();
    private String date;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        NomFunda2 = new javax.swing.JLabel();
        NombreEst2 = new javax.swing.JLabel();
        CNombreEst2 = new javax.swing.JTextField();
        ApelliEst3 = new javax.swing.JLabel();
        CApelliEst3 = new javax.swing.JTextField();
        CodigoEst2 = new javax.swing.JLabel();
        CCodiest2 = new javax.swing.JTextField();
        DatGene2 = new javax.swing.JLabel();
        DocumenEst2 = new javax.swing.JLabel();
        CdocumEst4 = new javax.swing.JComboBox<>();
        FechaNacEst2 = new javax.swing.JLabel();
        NumeroEst2 = new javax.swing.JLabel();
        CNumEst2 = new javax.swing.JTextField();
        Ciudad2 = new javax.swing.JLabel();
        CCiudad2 = new javax.swing.JTextField();
        DatMed2 = new javax.swing.JLabel();
        Sisben2 = new javax.swing.JLabel();
        CSisben2 = new javax.swing.JTextField();
        Eps2 = new javax.swing.JLabel();
        CEps2 = new javax.swing.JTextField();
        TipoSangre2 = new javax.swing.JLabel();
        Discapacidad2 = new javax.swing.JLabel();
        CTipoSangre2 = new javax.swing.JTextField();
        CdocumEst5 = new javax.swing.JComboBox<>();
        NonbreIncap2 = new javax.swing.JLabel();
        CNomInca2 = new javax.swing.JLabel();
        AlerMedic2 = new javax.swing.JLabel();
        CAlerMedi2 = new javax.swing.JComboBox<>();
        CAlergMed2 = new javax.swing.JLabel();
        CAlerAlim4 = new javax.swing.JLabel();
        AlerAlim4 = new javax.swing.JLabel();
        CAlergAlim4 = new javax.swing.JComboBox<>();
        AlerAlim5 = new javax.swing.JLabel();
        CAlergAlim5 = new javax.swing.JComboBox<>();
        CAlerAlim5 = new javax.swing.JLabel();
        DatAcudi2 = new javax.swing.JLabel();
        NombresAcud2 = new javax.swing.JLabel();
        CNomAcud4 = new javax.swing.JTextField();
        Apellidos2 = new javax.swing.JLabel();
        CNomAcud5 = new javax.swing.JTextField();
        DirecciónAcud2 = new javax.swing.JLabel();
        CDireccAcud2 = new javax.swing.JTextField();
        BarrioAcud2 = new javax.swing.JLabel();
        CBarrioAcud2 = new javax.swing.JTextField();
        CalularAcud2 = new javax.swing.JLabel();
        CCelularAcud2 = new javax.swing.JTextField();
        FijoAcud2 = new javax.swing.JLabel();
        CFijoAcud2 = new javax.swing.JTextField();
        DatAcademicos2 = new javax.swing.JLabel();
        Teatro2 = new javax.swing.JLabel();
        CTeatro2 = new javax.swing.JTextField();
        Danzas2 = new javax.swing.JLabel();
        CDanzas2 = new javax.swing.JTextField();
        Musica2 = new javax.swing.JLabel();
        CMusica2 = new javax.swing.JTextField();
        EducComplemen2 = new javax.swing.JLabel();
        CEducCompleme2 = new javax.swing.JTextField();
        EducAlmas2 = new javax.swing.JLabel();
        CEducAlmas2 = new javax.swing.JTextField();
        AlimentoConAmor2 = new javax.swing.JLabel();
        CAlimenConAmor2 = new javax.swing.JTextField();
        ImagenEst2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        siguiente2 = new javax.swing.JButton();
        jBAnterior2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setPreferredSize(new java.awt.Dimension(1070, 2000));

        NomFunda2.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        NomFunda2.setText("PERFIL ESTUDIANTE");

        NombreEst2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        NombreEst2.setText("Nombre:");

        ApelliEst3.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        ApelliEst3.setText("Apellidos:");

        CodigoEst2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        CodigoEst2.setText("Código:");

        DatGene2.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        DatGene2.setText("Datos Generales");

        DocumenEst2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        DocumenEst2.setText("Documento:");

        CdocumEst4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo" }));

        FechaNacEst2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        FechaNacEst2.setText("Fecha Nacimiento:");

        NumeroEst2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        NumeroEst2.setText("Número:");

        Ciudad2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        Ciudad2.setText("Ciudad:");

        DatMed2.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        DatMed2.setText("Datos Médicos");

        Sisben2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        Sisben2.setText("Sisben:");

        Eps2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        Eps2.setText("Eps:");

        TipoSangre2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        TipoSangre2.setText("Tipo de Sangre:");

        Discapacidad2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        Discapacidad2.setText("Discapacidad :");

        CdocumEst5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo" }));

        NonbreIncap2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        NonbreIncap2.setText("Nombre la incapacidad:");

        CNomInca2.setText("Describa cual o cuales");
        CNomInca2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        AlerMedic2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        AlerMedic2.setText("Alergico a algún medicamento:");

        CAlerMedi2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opciòn" }));

        CAlergMed2.setText("Describa cual o cuales");
        CAlergMed2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        CAlerAlim4.setText("Describa cual o cuales");
        CAlerAlim4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        AlerAlim4.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        AlerAlim4.setText("Alergico a algún alimento:");

        CAlergAlim4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opciòn" }));

        AlerAlim5.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        AlerAlim5.setText("Toma algún medicameno:");

        CAlergAlim5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opciòn" }));

        CAlerAlim5.setText("Describa cual o cuales");
        CAlerAlim5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        DatAcudi2.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        DatAcudi2.setText("Datos Acudiente");

        NombresAcud2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        NombresAcud2.setText("Nombres:");

        Apellidos2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        Apellidos2.setText("Apellidos:");

        DirecciónAcud2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        DirecciónAcud2.setText("Dirección:");

        BarrioAcud2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        BarrioAcud2.setText("Barrio:");

        CalularAcud2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        CalularAcud2.setText("Celular:");

        FijoAcud2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        FijoAcud2.setText("Fijo:");

        DatAcademicos2.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        DatAcademicos2.setText("Datos Académicos");

        Teatro2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        Teatro2.setText("Teatro:");

        CTeatro2.setText("Observaciones....");

        Danzas2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        Danzas2.setText("Danzas:");

        CDanzas2.setText("Observaciones....");

        Musica2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        Musica2.setText("Música :");

        CMusica2.setText("Observaciones....");

        EducComplemen2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        EducComplemen2.setText("Educación Complementaria:");

        CEducCompleme2.setText("Observaciones....");

        EducAlmas2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        EducAlmas2.setText("Educando Almas:");

        CEducAlmas2.setText("Observaciones....");

        AlimentoConAmor2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        AlimentoConAmor2.setText("Alimento con amor:");

        CAlimenConAmor2.setText("Observaciones....");

        ImagenEst2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPanel8.setBackground(new java.awt.Color(204, 204, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 138, Short.MAX_VALUE)
        );

        jPanel9.setBackground(new java.awt.Color(204, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 658, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        siguiente2.setBackground(new java.awt.Color(204, 204, 204));
        siguiente2.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        siguiente2.setText("siguiente");
        siguiente2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        siguiente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguiente2ActionPerformed(evt);
            }
        });

        jBAnterior2.setBackground(new java.awt.Color(204, 204, 204));
        jBAnterior2.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jBAnterior2.setText("Anterior");
        jBAnterior2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBAnterior2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAnterior2ActionPerformed(evt);
            }
        });

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jSeparator3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jSeparator4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(NomFunda2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(NombreEst2)
                        .addGap(22, 22, 22)
                        .addComponent(CNombreEst2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(ApelliEst3)
                        .addGap(15, 15, 15)
                        .addComponent(CApelliEst3, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(CCodiest2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(140, 140, 140)
                .addComponent(ImagenEst2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(CodigoEst2))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(430, 430, 430)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1040, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(450, 450, 450)
                .addComponent(DatGene2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(DocumenEst2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(CdocumEst4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(NumeroEst2)
                .addGap(22, 22, 22)
                .addComponent(CNumEst2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(FechaNacEst2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170)
                .addComponent(Ciudad2)
                .addGap(18, 18, 18)
                .addComponent(CCiudad2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 1050, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(470, 470, 470)
                .addComponent(DatMed2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Sisben2)
                .addGap(68, 68, 68)
                .addComponent(CSisben2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(Eps2)
                .addGap(36, 36, 36)
                .addComponent(CEps2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(TipoSangre2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(CTipoSangre2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Discapacidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(CdocumEst5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(NonbreIncap2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(CNomInca2, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(AlerMedic2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140)
                .addComponent(CAlerMedi2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(CAlergMed2, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(AlerAlim4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140)
                .addComponent(CAlergAlim4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(CAlerAlim4, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(AlerAlim5, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140)
                .addComponent(CAlergAlim5, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(CAlerAlim5, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 1040, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(450, 450, 450)
                .addComponent(DatAcudi2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(NombresAcud2)
                .addGap(15, 15, 15)
                .addComponent(CNomAcud4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Apellidos2)
                .addGap(15, 15, 15)
                .addComponent(CNomAcud5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(DirecciónAcud2)
                .addGap(13, 13, 13)
                .addComponent(CDireccAcud2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(BarrioAcud2)
                .addGap(22, 22, 22)
                .addComponent(CBarrioAcud2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(CalularAcud2)
                .addGap(27, 27, 27)
                .addComponent(CCelularAcud2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(FijoAcud2)
                .addGap(48, 48, 48)
                .addComponent(CFijoAcud2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Teatro2)
                .addGap(390, 390, 390)
                .addComponent(DatAcademicos2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(CTeatro2, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Danzas2))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(CDanzas2, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Musica2))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(CMusica2, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(EducComplemen2))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(CEducCompleme2, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(EducAlmas2))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(CEducAlmas2, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(AlimentoConAmor2))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(CAlimenConAmor2, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(730, 730, 730)
                .addComponent(siguiente2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jBAnterior2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(NomFunda2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NombreEst2)
                            .addComponent(CNombreEst2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ApelliEst3)
                            .addComponent(CApelliEst3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addComponent(CCodiest2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(ImagenEst2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(CodigoEst2))
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(DatGene2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NumeroEst2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DocumenEst2)
                            .addComponent(CdocumEst4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CNumEst2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FechaNacEst2)
                            .addComponent(Ciudad2)
                            .addComponent(CCiudad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(58, 58, 58)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(DatMed2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Sisben2)
                    .addComponent(CSisben2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Eps2)
                    .addComponent(CEps2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TipoSangre2)
                    .addComponent(CTipoSangre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Discapacidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CdocumEst5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(NonbreIncap2)
                .addGap(4, 4, 4)
                .addComponent(CNomInca2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AlerMedic2)
                    .addComponent(CAlerMedi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(CAlergMed2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AlerAlim4)
                    .addComponent(CAlergAlim4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(CAlerAlim4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AlerAlim5)
                    .addComponent(CAlergAlim5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(CAlerAlim5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(DatAcudi2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NombresAcud2)
                    .addComponent(CNomAcud4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Apellidos2)
                    .addComponent(CNomAcud5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DirecciónAcud2)
                    .addComponent(CDireccAcud2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BarrioAcud2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CBarrioAcud2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CalularAcud2)
                    .addComponent(CCelularAcud2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FijoAcud2)
                    .addComponent(CFijoAcud2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Teatro2))
                    .addComponent(DatAcademicos2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(CTeatro2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Danzas2)
                .addGap(4, 4, 4)
                .addComponent(CDanzas2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Musica2)
                .addGap(4, 4, 4)
                .addComponent(CMusica2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(EducComplemen2)
                .addGap(4, 4, 4)
                .addComponent(CEducCompleme2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(EducAlmas2)
                .addGap(4, 4, 4)
                .addComponent(CEducAlmas2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(AlimentoConAmor2)
                .addGap(4, 4, 4)
                .addComponent(CAlimenConAmor2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(siguiente2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBAnterior2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jScrollPane1.setViewportView(jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 2000, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {                                            
//        
//        //Metodo para cambiar el formato de fecha
//        SimpleDateFormat sdf = new SimpleDateFormat("dd-MMMM-yyyy");
//        String date = sdf.format(Date_fecha_naci.getDate());
//        
//        // Para setear (llenar) la informacion en el modelo Personas
//        pestudiante.setPeestNombres((String) box_tipo_documento.getSelectedItem());
//        persona.setPerNumerodeDocumento(Campo_num_documento.getText());
//        persona.setPerLugardeExpedicion(Campo_lugar_expe1.getText());
//        persona.setPerNombres(Campo_nombres1.getText());
//        persona.setPerApellidos(Campo_apellidos1.getText());
//        persona.setPerFotografia(Campo_foto.getText());
//        persona.setPerFechadeNacimiento(date);
//        persona.setPerEdad(Campo_edad.getText());
//        persona.setPerCiudadNacimiento(Campo_ciudad_nacimiento.getText());
//        persona.setPerDomicilio(Campo_domicilio.getText());
//        persona.setPerBarrio(Campo_barrio.getText());
//        persona.setPerLocalidad(Campo_localidad.getText());        
//        persona.setPerEstrato(Campo_estrato1.getText());       
//        persona.setPerEps(Campo_eps.getText());
//        if(Radio_sisben_si.isSelected()) {
//                persona.setPerSisben(true);
//        };
//        if(Radio_sisben_no.isSelected()) {
//            persona.setPerSisben(false);
//        }
//        persona.setPerSisbenCategoria(Campo_categoria_sis1.getText());
//        
//        
//        
//        boolean respuesta = registro.registrar(persona);
//        
//        //Si se guardo con exito, entonces
//        if(respuesta) {
//            
//           //QUe le muestre al usuario una ventana
//           JOptionPane.showMessageDialog(rootPane, "Se guardó con éxito", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
//           
//           //Y aqui que limpie
//           box_tipo_documento.setSelectedIndex(0);
//           Campo_num_documento.setText("");
//           Campo_lugar_expe1.setText("");
//           Campo_nombres1.setText("");
//           Campo_apellidos1.setText("");
//           Campo_foto.setText("");
//           Date_fecha_naci.setDateFormatString("01-01-2000"); //revisar
//           Campo_edad.setText(""); 
//           Campo_ciudad_nacimiento.setText("");
//           Campo_domicilio.setText("");
//           Campo_barrio.setText("");
//           Campo_localidad.setText("");
//           Campo_estrato1.setText("");
//           Campo_eps.setText("");
//           Campo_categoria_sis1.setText("");
//   
//        }
//         
//    }                               
    private void siguiente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguiente2ActionPerformed
        this.dispose();
        Notificaciones  abrir= new Notificaciones();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_siguiente2ActionPerformed

    private void jBAnterior2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAnterior2ActionPerformed
        this.dispose();
        PerfilAdministrador  abrir= new PerfilAdministrador();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBAnterior2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlerAlim4;
    private javax.swing.JLabel AlerAlim5;
    private javax.swing.JLabel AlerMedic2;
    private javax.swing.JLabel AlimentoConAmor2;
    public javax.swing.JLabel ApelliEst3;
    private javax.swing.JLabel Apellidos2;
    private javax.swing.JLabel BarrioAcud2;
    private javax.swing.JLabel CAlerAlim4;
    private javax.swing.JLabel CAlerAlim5;
    private javax.swing.JComboBox<String> CAlerMedi2;
    private javax.swing.JComboBox<String> CAlergAlim4;
    private javax.swing.JComboBox<String> CAlergAlim5;
    private javax.swing.JLabel CAlergMed2;
    private javax.swing.JTextField CAlimenConAmor2;
    public javax.swing.JTextField CApelliEst3;
    private javax.swing.JTextField CBarrioAcud2;
    private javax.swing.JTextField CCelularAcud2;
    private javax.swing.JTextField CCiudad2;
    public javax.swing.JTextField CCodiest2;
    private javax.swing.JTextField CDanzas2;
    private javax.swing.JTextField CDireccAcud2;
    private javax.swing.JTextField CEducAlmas2;
    private javax.swing.JTextField CEducCompleme2;
    private javax.swing.JTextField CEps2;
    private javax.swing.JTextField CFijoAcud2;
    private javax.swing.JTextField CMusica2;
    private javax.swing.JTextField CNomAcud4;
    private javax.swing.JTextField CNomAcud5;
    private javax.swing.JLabel CNomInca2;
    public javax.swing.JTextField CNombreEst2;
    private javax.swing.JTextField CNumEst2;
    private javax.swing.JTextField CSisben2;
    private javax.swing.JTextField CTeatro2;
    private javax.swing.JTextField CTipoSangre2;
    private javax.swing.JLabel CalularAcud2;
    private javax.swing.JComboBox<String> CdocumEst4;
    private javax.swing.JComboBox<String> CdocumEst5;
    private javax.swing.JLabel Ciudad2;
    public javax.swing.JLabel CodigoEst2;
    private javax.swing.JLabel Danzas2;
    private javax.swing.JLabel DatAcademicos2;
    private javax.swing.JLabel DatAcudi2;
    private javax.swing.JLabel DatGene2;
    private javax.swing.JLabel DatMed2;
    private javax.swing.JLabel DirecciónAcud2;
    private javax.swing.JLabel Discapacidad2;
    private javax.swing.JLabel DocumenEst2;
    private javax.swing.JLabel EducAlmas2;
    private javax.swing.JLabel EducComplemen2;
    private javax.swing.JLabel Eps2;
    private javax.swing.JLabel FechaNacEst2;
    private javax.swing.JLabel FijoAcud2;
    private javax.swing.JLabel ImagenEst2;
    private javax.swing.JLabel Musica2;
    public javax.swing.JLabel NomFunda2;
    public javax.swing.JLabel NombreEst2;
    private javax.swing.JLabel NombresAcud2;
    private javax.swing.JLabel NonbreIncap2;
    private javax.swing.JLabel NumeroEst2;
    private javax.swing.JLabel Sisben2;
    private javax.swing.JLabel Teatro2;
    private javax.swing.JLabel TipoSangre2;
    private javax.swing.JButton jBAnterior2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton siguiente2;
    // End of variables declaration//GEN-END:variables
}
