/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.fundacion.vistas;

/**
 *
 * @author USUARIO
 */
public class PerfilCoordinador extends javax.swing.JFrame {

    /**
     * Creates new form PerfilCoordinador2
     */
    public PerfilCoordinador() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        setTitle("PERFIL DEL COORDINADOR");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        PerfCoord = new javax.swing.JLabel();
        btn_perfil = new javax.swing.JButton();
        BotInscrip = new javax.swing.JButton();
        btn_listados = new javax.swing.JButton();
        BotNotif = new javax.swing.JButton();
        NombresPC = new javax.swing.JLabel();
        CamNombre = new javax.swing.JTextField();
        ApelliPC = new javax.swing.JLabel();
        CamApellidos = new javax.swing.JTextField();
        Documento = new javax.swing.JLabel();
        CamDocPC = new javax.swing.JTextField();
        CodPC = new javax.swing.JLabel();
        CamCodPC = new javax.swing.JTextField();
        DirecPC = new javax.swing.JLabel();
        CampDirPC = new javax.swing.JTextField();
        TelePC = new javax.swing.JLabel();
        CamTelPC = new javax.swing.JTextField();
        RolPC = new javax.swing.JLabel();
        CamRolPC = new javax.swing.JTextField();
        FecNacPC = new javax.swing.JLabel();
        CamImagPC = new javax.swing.JPanel();
        BotSigPerCoor = new javax.swing.JButton();
        BotAtrPerCoor = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        PerfCoord.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        PerfCoord.setText("PERFIL COORDINADOR");

        btn_perfil.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        btn_perfil.setText("Perfil");
        btn_perfil.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_perfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_perfilMouseClicked(evt);
            }
        });

        BotInscrip.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        BotInscrip.setText("Inscripciones");
        BotInscrip.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotInscrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotInscripActionPerformed(evt);
            }
        });

        btn_listados.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        btn_listados.setText("Listados");
        btn_listados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_listados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_listadosMouseClicked(evt);
            }
        });

        BotNotif.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        BotNotif.setText("Notificaciones");
        BotNotif.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotNotif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotNotifMouseClicked(evt);
            }
        });

        NombresPC.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        NombresPC.setText("Nombres:");

        CamNombre.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        CamNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        ApelliPC.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        ApelliPC.setText("Apellidos:");

        CamApellidos.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        CamApellidos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        Documento.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Documento.setText("Documento:");

        CamDocPC.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        CamDocPC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        CodPC.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        CodPC.setText("Codigo:");

        CamCodPC.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        CamCodPC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        DirecPC.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        DirecPC.setText("Direccion:");

        CampDirPC.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        CampDirPC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        TelePC.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        TelePC.setText("Telefono:");

        CamTelPC.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        CamTelPC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        RolPC.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        RolPC.setText("Rol:");

        CamRolPC.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        CamRolPC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        FecNacPC.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        FecNacPC.setText("Fecha de nacimiento:");

        CamImagPC.setBackground(new java.awt.Color(255, 255, 255));
        CamImagPC.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout CamImagPCLayout = new javax.swing.GroupLayout(CamImagPC);
        CamImagPC.setLayout(CamImagPCLayout);
        CamImagPCLayout.setHorizontalGroup(
            CamImagPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 156, Short.MAX_VALUE)
        );
        CamImagPCLayout.setVerticalGroup(
            CamImagPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 206, Short.MAX_VALUE)
        );

        BotSigPerCoor.setBackground(new java.awt.Color(204, 204, 204));
        BotSigPerCoor.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        BotSigPerCoor.setText("SIGUIENTE");
        BotSigPerCoor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotSigPerCoor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotSigPerCoorActionPerformed(evt);
            }
        });

        BotAtrPerCoor.setBackground(new java.awt.Color(204, 204, 204));
        BotAtrPerCoor.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        BotAtrPerCoor.setText("ATRAS");
        BotAtrPerCoor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotAtrPerCoor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotAtrPerCoorMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(PerfCoord, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(btn_perfil)
                .addGap(109, 109, 109)
                .addComponent(BotNotif)
                .addGap(116, 116, 116)
                .addComponent(btn_listados)
                .addGap(97, 97, 97)
                .addComponent(BotInscrip))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NombresPC, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ApelliPC, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Documento, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CodPC, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DirecPC, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CamNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CamApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CamDocPC, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CamCodPC, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampDirPC, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(140, 140, 140)
                .addComponent(CamImagPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(CamTelPC, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TelePC, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RolPC, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(CamRolPC, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(FecNacPC, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(370, 370, 370)
                .addComponent(BotSigPerCoor, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(BotAtrPerCoor, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(PerfCoord, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_perfil)
                    .addComponent(BotNotif)
                    .addComponent(btn_listados)
                    .addComponent(BotInscrip))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NombresPC, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CamNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CamApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ApelliPC, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CamDocPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Documento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CodPC, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CamCodPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(CampDirPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(DirecPC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(CamImagPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CamTelPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TelePC, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RolPC, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CamRolPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(FecNacPC))
                    .addComponent(BotSigPerCoor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotAtrPerCoor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_perfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_perfilMouseClicked

    }//GEN-LAST:event_btn_perfilMouseClicked

    private void BotInscripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotInscripActionPerformed
        this.dispose();
        inscripciones abrir = new inscripciones();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotInscripActionPerformed

    private void btn_listadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_listadosMouseClicked
        this.dispose();
        Listado_Estudiantes abrir = new Listado_Estudiantes();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_listadosMouseClicked

    private void BotNotifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotNotifMouseClicked
        this.dispose();
        Notificaciones abrir = new Notificaciones();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotNotifMouseClicked

    private void BotSigPerCoorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotSigPerCoorActionPerformed
        this.dispose();
        perfil_profesor abrir = new perfil_profesor();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotSigPerCoorActionPerformed

    private void BotAtrPerCoorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotAtrPerCoorMouseClicked
        this.dispose();
        PerfilAdministrador abrir = new PerfilAdministrador();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotAtrPerCoorMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApelliPC;
    private javax.swing.JButton BotAtrPerCoor;
    private javax.swing.JButton BotInscrip;
    private javax.swing.JButton BotNotif;
    private javax.swing.JButton BotSigPerCoor;
    private javax.swing.JTextField CamApellidos;
    private javax.swing.JTextField CamCodPC;
    private javax.swing.JTextField CamDocPC;
    private javax.swing.JPanel CamImagPC;
    private javax.swing.JTextField CamNombre;
    private javax.swing.JTextField CamRolPC;
    private javax.swing.JTextField CamTelPC;
    private javax.swing.JTextField CampDirPC;
    private javax.swing.JLabel CodPC;
    private javax.swing.JLabel DirecPC;
    private javax.swing.JLabel Documento;
    private javax.swing.JLabel FecNacPC;
    private javax.swing.JLabel NombresPC;
    private javax.swing.JLabel PerfCoord;
    private javax.swing.JLabel RolPC;
    private javax.swing.JLabel TelePC;
    private javax.swing.JButton btn_listados;
    private javax.swing.JButton btn_perfil;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
