/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.fundacion.vistas;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
/**
 *
 * @author USUARIO
 */
public class Perfil_estudiante extends javax.swing.JFrame {

    /**
     * Creates new form Perfil_estudiante
     */
    public Perfil_estudiante() {
        initComponents();;
        setVisible(true);
        setLocationRelativeTo(null);
        setTitle("PERFIL DEL ESTUDIANTE");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        NombreEst2 = new javax.swing.JLabel();
        CNombreEst2 = new javax.swing.JTextField();
        ApelliEst3 = new javax.swing.JLabel();
        CApelliEst3 = new javax.swing.JTextField();
        CodigoEst2 = new javax.swing.JLabel();
        CCodiest2 = new javax.swing.JTextField();
        DatGene2 = new javax.swing.JLabel();
        DocumenEst2 = new javax.swing.JLabel();
        CdocumEst4 = new javax.swing.JComboBox<>();
        FechaNacEst2 = new javax.swing.JLabel();
        NumeroEst2 = new javax.swing.JLabel();
        CNumEst2 = new javax.swing.JTextField();
        Ciudad2 = new javax.swing.JLabel();
        CCiudad2 = new javax.swing.JTextField();
        DatMed2 = new javax.swing.JLabel();
        Sisben2 = new javax.swing.JLabel();
        CSisben2 = new javax.swing.JTextField();
        Eps2 = new javax.swing.JLabel();
        CEps2 = new javax.swing.JTextField();
        TipoSangre2 = new javax.swing.JLabel();
        Discapacidad2 = new javax.swing.JLabel();
        CTipoSangre2 = new javax.swing.JTextField();
        CdocumEst5 = new javax.swing.JComboBox<>();
        NonbreIncap2 = new javax.swing.JLabel();
        CNomInca2 = new javax.swing.JLabel();
        AlerMedic2 = new javax.swing.JLabel();
        CAlerMedi2 = new javax.swing.JComboBox<>();
        CAlergMed2 = new javax.swing.JLabel();
        CAlerAlim4 = new javax.swing.JLabel();
        AlerAlim4 = new javax.swing.JLabel();
        CAlergAlim4 = new javax.swing.JComboBox<>();
        AlerAlim5 = new javax.swing.JLabel();
        CAlergAlim5 = new javax.swing.JComboBox<>();
        CAlerAlim5 = new javax.swing.JLabel();
        DatAcudi2 = new javax.swing.JLabel();
        NombresAcud2 = new javax.swing.JLabel();
        CNomAcud4 = new javax.swing.JTextField();
        Apellidos2 = new javax.swing.JLabel();
        CNomAcud5 = new javax.swing.JTextField();
        DirecciónAcud2 = new javax.swing.JLabel();
        CDireccAcud2 = new javax.swing.JTextField();
        BarrioAcud2 = new javax.swing.JLabel();
        CBarrioAcud2 = new javax.swing.JTextField();
        CalularAcud2 = new javax.swing.JLabel();
        CCelularAcud2 = new javax.swing.JTextField();
        FijoAcud2 = new javax.swing.JLabel();
        CFijoAcud2 = new javax.swing.JTextField();
        DatAcademicos2 = new javax.swing.JLabel();
        Teatro2 = new javax.swing.JLabel();
        CTeatro2 = new javax.swing.JTextField();
        Danzas2 = new javax.swing.JLabel();
        CDanzas2 = new javax.swing.JTextField();
        Musica2 = new javax.swing.JLabel();
        CMusica2 = new javax.swing.JTextField();
        EducComplemen2 = new javax.swing.JLabel();
        CEducCompleme2 = new javax.swing.JTextField();
        EducAlmas2 = new javax.swing.JLabel();
        CEducAlmas2 = new javax.swing.JTextField();
        AlimentoConAmor2 = new javax.swing.JLabel();
        CAlimenConAmor2 = new javax.swing.JTextField();
        ImagenEst2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        NomFunda2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jBAnterior2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setPreferredSize(new java.awt.Dimension(1070, 2000));

        NombreEst2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        NombreEst2.setText("Nombre:");

        ApelliEst3.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        ApelliEst3.setText("Apellidos:");

        CodigoEst2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        CodigoEst2.setText("Código:");

        DatGene2.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        DatGene2.setText("Datos Generales");

        DocumenEst2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        DocumenEst2.setText("Documento:");

        CdocumEst4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo" }));

        FechaNacEst2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        FechaNacEst2.setText("Fecha Nacimiento:");

        NumeroEst2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        NumeroEst2.setText("Número:");

        Ciudad2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        Ciudad2.setText("Ciudad:");

        DatMed2.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        DatMed2.setText("Datos Médicos");

        Sisben2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        Sisben2.setText("Sisben:");

        Eps2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        Eps2.setText("Eps:");

        TipoSangre2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        TipoSangre2.setText("Tipo de Sangre:");

        Discapacidad2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        Discapacidad2.setText("Discapacidad :");

        CdocumEst5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo" }));

        NonbreIncap2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        NonbreIncap2.setText("Nombre la incapacidad:");

        CNomInca2.setText("Describa cual o cuales");
        CNomInca2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        AlerMedic2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        AlerMedic2.setText("Alergico a algún medicamento:");

        CAlerMedi2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opciòn" }));

        CAlergMed2.setText("Describa cual o cuales");
        CAlergMed2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        CAlerAlim4.setText("Describa cual o cuales");
        CAlerAlim4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        AlerAlim4.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        AlerAlim4.setText("Alergico a algún alimento:");

        CAlergAlim4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opciòn" }));

        AlerAlim5.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        AlerAlim5.setText("Toma algún medicameno:");

        CAlergAlim5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opciòn" }));

        CAlerAlim5.setText("Describa cual o cuales");
        CAlerAlim5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        DatAcudi2.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        DatAcudi2.setText("Datos Acudiente");

        NombresAcud2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        NombresAcud2.setText("Nombres:");

        Apellidos2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        Apellidos2.setText("Apellidos:");

        DirecciónAcud2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        DirecciónAcud2.setText("Dirección:");

        BarrioAcud2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        BarrioAcud2.setText("Barrio:");

        CalularAcud2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        CalularAcud2.setText("Celular:");

        FijoAcud2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        FijoAcud2.setText("Fijo:");

        DatAcademicos2.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        DatAcademicos2.setText("Datos Académicos");

        Teatro2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        Teatro2.setText("Teatro:");

        CTeatro2.setText("Observaciones....");

        Danzas2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        Danzas2.setText("Danzas:");

        CDanzas2.setText("Observaciones....");

        Musica2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        Musica2.setText("Música :");

        CMusica2.setText("Observaciones....");

        EducComplemen2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        EducComplemen2.setText("Educación Complementaria:");

        CEducCompleme2.setText("Observaciones....");

        EducAlmas2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        EducAlmas2.setText("Educando Almas:");

        CEducAlmas2.setText("Observaciones....");

        AlimentoConAmor2.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        AlimentoConAmor2.setText("Alimento con amor:");

        CAlimenConAmor2.setText("Observaciones....");

        ImagenEst2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPanel8.setBackground(new java.awt.Color(204, 204, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        NomFunda2.setFont(new java.awt.Font("Lucida Fax", 1, 24)); // NOI18N
        NomFunda2.setText("PERFIL ESTUDIANTE");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/fundacion/imagenes/logoFNH2.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 395, Short.MAX_VALUE)
                .addComponent(NomFunda2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(321, 321, 321))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NomFunda2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        jBAnterior2.setBackground(new java.awt.Color(255, 255, 255));
        jBAnterior2.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jBAnterior2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/fundacion/imagenes/icons8-izquierda-32.png"))); // NOI18N
        jBAnterior2.setText("Volver");
        jBAnterior2.setBorder(null);
        jBAnterior2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAnterior2ActionPerformed(evt);
            }
        });

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jSeparator3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jSeparator4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(DocumenEst2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CdocumEst4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(NumeroEst2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CNumEst2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(FechaNacEst2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Ciudad2)
                        .addGap(18, 18, 18)
                        .addComponent(CCiudad2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(NonbreIncap2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(AlerMedic2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140)
                        .addComponent(CAlerMedi2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(AlerAlim4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140)
                        .addComponent(CAlergAlim4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(AlerAlim5, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140)
                        .addComponent(CAlergAlim5, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(NombreEst2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CNombreEst2, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(CodigoEst2)
                                    .addComponent(ApelliEst3))
                                .addGap(15, 15, 15)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CApelliEst3)
                                    .addComponent(CCodiest2, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(114, 114, 114)
                        .addComponent(ImagenEst2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Teatro2)
                            .addComponent(CTeatro2, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Danzas2)
                            .addComponent(CDanzas2, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Musica2)
                            .addComponent(CMusica2, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EducComplemen2)
                            .addComponent(CEducCompleme2, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EducAlmas2)
                            .addComponent(CEducAlmas2, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AlimentoConAmor2)
                            .addComponent(CAlimenConAmor2, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBAnterior2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(NombresAcud2)
                                .addGap(15, 15, 15)
                                .addComponent(CNomAcud4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(Apellidos2)
                                .addGap(15, 15, 15)
                                .addComponent(CNomAcud5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(DirecciónAcud2)
                                .addGap(13, 13, 13)
                                .addComponent(CDireccAcud2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(BarrioAcud2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CBarrioAcud2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(CalularAcud2)
                                .addGap(27, 27, 27)
                                .addComponent(CCelularAcud2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(FijoAcud2)
                                .addGap(48, 48, 48)
                                .addComponent(CFijoAcud2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(449, 449, 449)
                        .addComponent(DatMed2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(463, 463, 463)
                        .addComponent(DatAcudi2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(451, 451, 451)
                        .addComponent(DatAcademicos2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 1028, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1018, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(Sisben2)
                            .addGap(68, 68, 68)
                            .addComponent(CSisben2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(60, 60, 60)
                            .addComponent(Eps2)
                            .addGap(36, 36, 36)
                            .addComponent(CEps2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(TipoSangre2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(CTipoSangre2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(Discapacidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(CdocumEst5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(CNomInca2, javax.swing.GroupLayout.PREFERRED_SIZE, 1026, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CAlergMed2, javax.swing.GroupLayout.PREFERRED_SIZE, 1026, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CAlerAlim4, javax.swing.GroupLayout.PREFERRED_SIZE, 1026, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 1026, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(CAlerAlim5, javax.swing.GroupLayout.PREFERRED_SIZE, 1026, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(442, 442, 442)
                        .addComponent(DatGene2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(ImagenEst2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NombreEst2)
                            .addComponent(CNombreEst2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ApelliEst3)
                            .addComponent(CApelliEst3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CodigoEst2)
                            .addComponent(CCodiest2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DatGene2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DocumenEst2)
                        .addComponent(CdocumEst4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CNumEst2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(NumeroEst2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(FechaNacEst2))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CCiudad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Ciudad2))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DatMed2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Sisben2)
                    .addComponent(CSisben2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Eps2)
                    .addComponent(CEps2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TipoSangre2)
                    .addComponent(CTipoSangre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Discapacidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CdocumEst5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(NonbreIncap2)
                .addGap(4, 4, 4)
                .addComponent(CNomInca2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AlerMedic2)
                    .addComponent(CAlerMedi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(CAlergMed2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AlerAlim4)
                    .addComponent(CAlergAlim4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(CAlerAlim4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AlerAlim5)
                    .addComponent(CAlergAlim5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(CAlerAlim5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(DatAcudi2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NombresAcud2)
                    .addComponent(CNomAcud4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Apellidos2)
                    .addComponent(CNomAcud5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DirecciónAcud2)
                    .addComponent(CDireccAcud2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BarrioAcud2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CBarrioAcud2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CalularAcud2)
                    .addComponent(CCelularAcud2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FijoAcud2)
                    .addComponent(CFijoAcud2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DatAcademicos2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Teatro2)
                .addGap(4, 4, 4)
                .addComponent(CTeatro2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Danzas2)
                .addGap(4, 4, 4)
                .addComponent(CDanzas2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Musica2)
                .addGap(4, 4, 4)
                .addComponent(CMusica2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EducComplemen2)
                .addGap(4, 4, 4)
                .addComponent(CEducCompleme2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EducAlmas2)
                .addGap(4, 4, 4)
                .addComponent(CEducAlmas2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AlimentoConAmor2)
                .addGap(4, 4, 4)
                .addComponent(CAlimenConAmor2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jBAnterior2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1887, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAnterior2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAnterior2ActionPerformed
        this.dispose();
        PerfilAdministrador  abrir= new PerfilAdministrador();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBAnterior2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlerAlim4;
    private javax.swing.JLabel AlerAlim5;
    private javax.swing.JLabel AlerMedic2;
    private javax.swing.JLabel AlimentoConAmor2;
    public javax.swing.JLabel ApelliEst3;
    private javax.swing.JLabel Apellidos2;
    private javax.swing.JLabel BarrioAcud2;
    private javax.swing.JLabel CAlerAlim4;
    private javax.swing.JLabel CAlerAlim5;
    private javax.swing.JComboBox<String> CAlerMedi2;
    private javax.swing.JComboBox<String> CAlergAlim4;
    private javax.swing.JComboBox<String> CAlergAlim5;
    private javax.swing.JLabel CAlergMed2;
    private javax.swing.JTextField CAlimenConAmor2;
    public javax.swing.JTextField CApelliEst3;
    private javax.swing.JTextField CBarrioAcud2;
    private javax.swing.JTextField CCelularAcud2;
    private javax.swing.JTextField CCiudad2;
    public javax.swing.JTextField CCodiest2;
    private javax.swing.JTextField CDanzas2;
    private javax.swing.JTextField CDireccAcud2;
    private javax.swing.JTextField CEducAlmas2;
    private javax.swing.JTextField CEducCompleme2;
    private javax.swing.JTextField CEps2;
    private javax.swing.JTextField CFijoAcud2;
    private javax.swing.JTextField CMusica2;
    private javax.swing.JTextField CNomAcud4;
    private javax.swing.JTextField CNomAcud5;
    private javax.swing.JLabel CNomInca2;
    public javax.swing.JTextField CNombreEst2;
    private javax.swing.JTextField CNumEst2;
    private javax.swing.JTextField CSisben2;
    private javax.swing.JTextField CTeatro2;
    private javax.swing.JTextField CTipoSangre2;
    private javax.swing.JLabel CalularAcud2;
    private javax.swing.JComboBox<String> CdocumEst4;
    private javax.swing.JComboBox<String> CdocumEst5;
    private javax.swing.JLabel Ciudad2;
    public javax.swing.JLabel CodigoEst2;
    private javax.swing.JLabel Danzas2;
    private javax.swing.JLabel DatAcademicos2;
    private javax.swing.JLabel DatAcudi2;
    private javax.swing.JLabel DatGene2;
    private javax.swing.JLabel DatMed2;
    private javax.swing.JLabel DirecciónAcud2;
    private javax.swing.JLabel Discapacidad2;
    private javax.swing.JLabel DocumenEst2;
    private javax.swing.JLabel EducAlmas2;
    private javax.swing.JLabel EducComplemen2;
    private javax.swing.JLabel Eps2;
    private javax.swing.JLabel FechaNacEst2;
    private javax.swing.JLabel FijoAcud2;
    private javax.swing.JLabel ImagenEst2;
    private javax.swing.JLabel Musica2;
    public javax.swing.JLabel NomFunda2;
    public javax.swing.JLabel NombreEst2;
    private javax.swing.JLabel NombresAcud2;
    private javax.swing.JLabel NonbreIncap2;
    private javax.swing.JLabel NumeroEst2;
    private javax.swing.JLabel Sisben2;
    private javax.swing.JLabel Teatro2;
    private javax.swing.JLabel TipoSangre2;
    private javax.swing.JButton jBAnterior2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
