/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.fundacion.vistas;

/**
 *
 * @author USUARIO
 */
public class psicologia extends javax.swing.JFrame {

    /**
     * Creates new form psicologia
     */
    public psicologia() {
        initComponents();
         setVisible(true);
        setLocationRelativeTo(null);
        setTitle("PSICOLOGÍA");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        Psicología = new javax.swing.JLabel();
        NombrePsicologo = new javax.swing.JLabel();
        SeleccioneEstudiante = new javax.swing.JComboBox<>();
        NombreEstu = new javax.swing.JLabel();
        Alerta = new javax.swing.JLabel();
        CampoAlerta = new javax.swing.JComboBox<>();
        CampoPrimSec = new java.awt.TextArea();
        CampoPrimSes = new javax.swing.JLabel();
        SegundaSesion = new javax.swing.JLabel();
        CampoSegSes = new java.awt.TextArea();
        CampoTercSes = new javax.swing.JLabel();
        CampoTercSec = new java.awt.TextArea();
        CampoObser = new javax.swing.JLabel();
        CampoObse = new java.awt.TextArea();
        CampoNomPsico1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        BotSigPsi = new javax.swing.JButton();
        jBIrANotificaciones = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Psicología.setBackground(new java.awt.Color(255, 255, 255));
        Psicología.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        Psicología.setText("PSICOLOGÍA");

        NombrePsicologo.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        NombrePsicologo.setText("Nombre Psicólogo");

        SeleccioneEstudiante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el Estudiante" }));
        SeleccioneEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccioneEstudianteActionPerformed(evt);
            }
        });

        NombreEstu.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        NombreEstu.setText("Nombre Estudiante");

        Alerta.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        Alerta.setText("Alerta creada por");

        CampoPrimSes.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        CampoPrimSes.setText("Primera sesión:");

        SegundaSesion.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        SegundaSesion.setText("Segunda sesión");

        CampoTercSes.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        CampoTercSes.setText("Tercera sesión");

        CampoObser.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        CampoObser.setText("Observaciones:");

        CampoNomPsico1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el Psicólogo" }));
        CampoNomPsico1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNomPsico1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        BotSigPsi.setBackground(new java.awt.Color(204, 204, 204));
        BotSigPsi.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        BotSigPsi.setText("IR AL PERFIL COORD");
        BotSigPsi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotSigPsi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotSigPsiMouseClicked(evt);
            }
        });

        jBIrANotificaciones.setBackground(new java.awt.Color(204, 204, 204));
        jBIrANotificaciones.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        jBIrANotificaciones.setText("IR A NOTIFICACIONES");
        jBIrANotificaciones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBIrANotificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIrANotificacionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Psicología, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(NombrePsicologo)
                .addGap(222, 222, 222)
                .addComponent(NombreEstu)
                .addGap(216, 216, 216)
                .addComponent(Alerta))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(CampoNomPsico1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(SeleccioneEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(CampoAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(CampoPrimSes))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(CampoPrimSec, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(SegundaSesion))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(CampoSegSes, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(CampoTercSes))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(CampoTercSec, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(CampoObser))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(CampoObse, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(650, 650, 650)
                .addComponent(BotSigPsi, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jBIrANotificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(Psicología)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NombrePsicologo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NombreEstu)
                            .addComponent(Alerta))))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CampoNomPsico1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SeleccioneEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CampoAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(CampoPrimSes)
                .addGap(4, 4, 4)
                .addComponent(CampoPrimSec, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(SegundaSesion)
                .addGap(4, 4, 4)
                .addComponent(CampoSegSes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(CampoTercSes)
                .addGap(4, 4, 4)
                .addComponent(CampoTercSec, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(CampoObser)
                .addGap(4, 4, 4)
                .addComponent(CampoObse, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(BotSigPsi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBIrANotificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SeleccioneEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccioneEstudianteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeleccioneEstudianteActionPerformed

    private void CampoNomPsico1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNomPsico1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNomPsico1ActionPerformed

    private void BotSigPsiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotSigPsiMouseClicked
        this.dispose();
        PerfilCoordinador abrir = new PerfilCoordinador();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotSigPsiMouseClicked

    private void jBIrANotificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIrANotificacionesActionPerformed
        this.dispose();
        Notificaciones abrir = new Notificaciones();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBIrANotificacionesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alerta;
    private javax.swing.JButton BotSigPsi;
    private javax.swing.JComboBox<String> CampoAlerta;
    private javax.swing.JComboBox<String> CampoNomPsico1;
    private java.awt.TextArea CampoObse;
    private javax.swing.JLabel CampoObser;
    private java.awt.TextArea CampoPrimSec;
    private javax.swing.JLabel CampoPrimSes;
    private java.awt.TextArea CampoSegSes;
    private java.awt.TextArea CampoTercSec;
    private javax.swing.JLabel CampoTercSes;
    private javax.swing.JLabel NombreEstu;
    private javax.swing.JLabel NombrePsicologo;
    private javax.swing.JLabel Psicología;
    private javax.swing.JLabel SegundaSesion;
    private javax.swing.JComboBox<String> SeleccioneEstudiante;
    private javax.swing.JButton jBIrANotificaciones;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
